language: node_js
node_js:
  - v13.13.0

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves for cypress tests
      - libgconf-2-4

before_install:
  - export TZ=America/New_York

install:
  - cd scraper

  - echo $MONGO_URI
  - node --version
  - pwd
  - npm install

  - cd backend
  - npm install
  - cd ..

before_script:
  - echo not doing any pre-scripts things...

script:
   - npm run scrape:headless

after_script:
  - echo ran script

after_success:
  - echo "I guess we're done here!"

matrix:
  fast_finish: true

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache